#lang sicp
(define (make-account balance password)
  (let ((limit 7)
        (count 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch msg m)
      (if (eq? msg password)
          (cond
            ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request: MAKE-ACCOUNT"
                         m)))
          (lambda (x)
            (cond ((> count limit)
                   (lambda () "call-the-cops"))
                  (else (begin (set! count (+ 1 count))
                               "Incorrect password"))))
         ))
   dispatch))
